//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by IVS_OCXPlayer.rc
//
#define IDS_IVS_OCXPLAYER               1
#define IDI_ABOUTDLL                    3
#define IDS_IVS_OCXPLAYER_PPG           4
#define IDS_OCX_PLAY_ZH                 5
#define IDS_OCX_PAUSE_ZH                6
#define IDS_OCX_STOP_ZH                 7
#define IDS_OCX_LOCAL_RECORD_ZH         8
#define IDS_OCX_STOP_RECORD_ZH          9
#define IDS_OCX_CAPTURE_ZH              10
#define IDS_OCX_LABEL_ZH                11
#define IDS_OCX_TALKBACK_ZH             12
#define IDS_OCX_SOUND_ZH                13
#define IDS_OCX_MAGNIFY_ZH              14
#define IDS_OCX_PTZ_ZH                  15
#define IDS_OCX_ALARM_ZH                16
#define IDS_OCX_TVWALL_ZH               17
#define IDS_OCX_ANALYSIS_ZH             18
#define IDS_OCX_RECTANGLE_ZH            19
#define IDS_OCX_POLYGON_ZH              20
#define IDS_OCX_STRAIGHT_ZH             21
#define IDS_OCX_UFORM_ZH                22
#define IDS_OCX_NFORM_ZH                23
#define IDS_OCX_MODIFY_ZH               24
#define IDS_OCX_DELETE_ZH               25
#define IDS_OCX_MAGNIFIER_ZH            26
#define IDS_OCX_MINIFIER_ZH             27
#define IDS_OCX_HAND_ZH                 28
#define IDS_OCX_CLOSE_ZH                29
#define IDS_OCX_INFO_ZH                 30
#define IDS_OCX_RECONNECT_ZH            31
#define IDD_POPTOOLBAR                  109
#define IDD_DLG_TVIDEOREALTIMEBAR       112
#define IDD_DLG_TVIDEOTITLEBAR          115
#define IDC_BUTTON_ANALYSIS_RECTANGLE7  120
#define IDD_DLG_TSENSETITLEBAR          124
#define IDC_BUTTON_ANALYSIS_SCREEN      126
#define IDC_BUTTON_REALTIME_LOCKER_ALARM 128
#define IDC_BUTTON_ANALYSIS_STOP        129
#define IDC_BUTTON_ANALYSIS_PLAY        132
#define IDC_BUTTON_REALTIME_LOCKER_WALL 134
#define IDC_BUTTON_ANALYSIS_STRAIGHT2   135
#define IDC_BUTTON_REALTIME_LOCKER_BAR  138
#define IDC_BUTTON_REALTIME_LOCKER_ALISYS 141
#define IDC_BUTTON_REALTIME_LOCKER_ANALYSIS 142
#define IDC_BUTTON_ANALYSIS_N           143
#define IDC_BTNTEST                     150
#define IDC_BTN_TITLE_S                 155
#define IDC_BTN_TITLE_OFF               155
#define IDC_BTN_TITLE_INF               156
#define IDC_BTN_TITLE_TVWALL_HANDLING   157
#define IDC_BTN_TITLE_INF3              158
#define IDC_BTN_TITLE_TVWALL_OK         158
#define IDC_BTN_TURNCRUISE              159
#define IDC_BTN_TITLE_TVWALL_VIDEO_BROKEN 160
#define IDC_BTN_RECORD_STATUS           161
#define IDC_BTN_RECT                    162
#define IDC_BTN_ALARM_STATUS            162
#define IDC_BTN_POLYGON                 163
#define IDC_SENSE_ADD                   163
#define IDC_BTN_CRUISETRACK_STATUS      163
#define IDC_BTN_ZOOM_IN                 164
#define IDC_SENSE_DELETE                164
#define IDC_BTN_SINGLEFRAME_STATUS      164
#define IDC_BTN_ZOOM_OUT                165
#define IDC_BTN_SINGLEFRAME_STATUS2     165
#define IDC_BTN_RECONNECT_STATUS        165
#define IDC_BTN_MOVE                    166
#define IDC_BTN_PRE                     166
#define IDC_BTN_DISPLAY_MODE            167
#define IDC_BUTTON2                     167
#define IDC_BTN_NEXT                    167
#define IDC_BTN_LEFT                    167
#define IDC_BTN_MAGNIFY                 167
#define IDC_BTN_PLAY                    168
#define IDC_BTN_TOP                     169
#define IDC_BTN_DELETE                  170
#define IDC_BTN_RIGHT                   170
#define IDC_BTN_BOTTOM                  171
#define IDC_COMBO_RATE                  172
#define IDC_BTN_SHRINK                  173
#define IDC_SLIDER_RATE                 174
#define IDC_CHECK_SOUNDCTRL             175
#define IDC_BTN_SNAPSHOT                175
#define IDC_BTN_PLAYBACK                176
#define IDC_SLIDER_SOUNDCTRL            177
#define IDC_TIMER                       177
#define IDC_BUTTON_SOUNDCTRL            179
#define IDC_MAGNIFY_TEXT                182
#define IDC_BUTTON_RECORD_ANALYSIS2     184
#define IDC_SLIDER_MAGBIFYCTRL          184
#define IDC_BTN_ZOOMOVER                185
#define IDC_ZOOM_NAME                   186
#define IDC_BTN_TOP_LEFT                187
#define IDC_BTN_TOP_RIGHT               188
#define IDC_BUTTON4                     189
#define IDC_BTN_BOTTOM_RIGTH            189
#define IDC_BTN_BOTTOM_LEFT             190
#define IDC_BTN_WATERMARK_STATUS        191
#define IDS_IVS_OCXPLAYER_PPG_CAPTION   241
#define IDD_PROPPAGE_IVS_OCXPLAYER      242
#define IDD_DLG_VIDEOPANE               245
#define IDD_DLG_PARENT                  265
#define IDC_CURSOR_EXCHANGE             268
#define IDR_RIGHT_BUTTON_MENU           269
#define IDC_CURSOR_EXCHANGE_WARN        270
#define IDB_IVS_OCXPLAYER               272
#define IDB_BITMAP_NOTTALKBACK          273
#define IDC_BUTTON_INFOR2               281
#define IDC_BUTTON_LOCKER               282
#define IDC_CURSOR_MAGNIFY              284
#define IDC_DEVNAME_TEXT                287
#define IDC_BUTTON_SERIAL_CAPTURE       291
#define IDC_BUTTON_RECORD               293
#define IDC_PIC_STATE_BACKGROUND        295
#define IDC_PIC_STATE_TURN              296
#define IDC_PIC_STATE_NAVIGATE          298
#define IDC_PIC_STATE_RECORD            300
#define IDC_PIC_STATE_ALARM             302
#define IDC_PIC_STATE_PLAYBACK          304
#define IDC_PIC_STATE_WATERMARK         306
#define IDC_PIC_STATE_SCALE             309
#define IDC_BUTTON_REPLAY_SOUND         330
#define IDC_STATIC_EAGLE_EYE            332
#define IDB_BITMAP_REALTIME_REPLAY_FOCUS 333
#define IDB_BITMAP_REALTIME_REPLAY_NORMAL 334
#define IDB_BITMAP_REALTIME_REPLAY_CLICK 335
#define IDD_DLG_SOUND_CONTRL            351
#define IDD_DLG_SOUNDCTRL               352
#define IDC_STATIC_VIDEO                353
#define IDB_BITMAP_SLIDER_THUMB_NORMAL  375
#define IDI_ICON_LOGO                   431
#define IDB_PNG_PLAY_NORMAL             447
#define IDB_PNG_PLAY_FOCUS              448
#define IDB_PNG_PLAY_GRAY               449
#define IDB_VIDEOPANE_BKG               452
#define IDB_PNG_STOP_NORMAL             456
#define IDB_PNG_STOP_FOCUS              457
#define IDB_PNG_STOP_GRAY               458
#define IDB_BITMAP1                     492
#define IDB_BITMAP_VIDEOPANE_ALARM      492
#define IDB_PNG_BG                      496
#define IDD_DLG_TSOUNDctrl              520
#define IDB_PNG4                        548
#define IDB_BITMAP2                     555
#define IDB_PNG_RETRACTED_GRAY          561
#define IDD_DLG_ANALYSISTOOLBAR         611
#define IDB_BITMAP_TALKBACK_NORMAL      612
#define IDB_BITMAP_NOSOUND_CLICK        613
#define IDB_BITMAP_NOSOUND_FOCUS        614
#define IDB_BITMAP_NOSOUND_GRAY         615
#define IDB_BITMAP_NOSOUND_NORMAL       616
#define IDB_BITMAP_NOTALKBACK_CLICK     617
#define IDB_BITMAP_NOTALKBACK_FOCUS     618
#define IDB_BITMAP_NOTALKBACK_GRAY      619
#define IDB_BITMAP_NOTALKBACK_NORMAL    620
#define IDB_BITMAP_SOUND_CLICK          621
#define IDB_BITMAP_SOUND_FOCUS          622
#define IDB_BITMAP_SOUND_GRAY           623
#define IDB_BITMAP_SOUND_NORMAL         624
#define IDB_BITMAP_TALKBACK_CLICK       625
#define IDB_BITMAP_TALKBACK_FOCUS       626
#define IDB_BITMAP_TALKBACK_GRAY        627
#define IDB_BITMAP_SIGN_NORMAL          628
#define IDB_BITMAP_SOUNDCTRL_SLIDER_CHANNEL 629
#define IDB_BITMAP_SOUNDCTRL_SLIDER_CHANNEL_ACTIVE 630
#define IDB_BITMAP6                     631
#define IDB_BITMAP_SIGN_CLICK           631
#define IDD_DIALOG_TVWALL_STATUSBAR     632
#define IDD_DLG_TVWALL_STATUSBAR        632
#define IDD_DLG_TURNCRUISEPANE          633
#define IDD_DLG_DITTAL_PTZ              634
#define IDD_DLG_ZOOMBAR                 635
#define IDD_DLG_PLAYBACKPANE            636
#define IDD_DLG_TIMERBAR                637
#define IDD_DLG_MAGNIFYCTRL             638
#define IDB_PNG1                        640
#define IDB_BITMAP_MAGBIFY_SIGN_CLICK   645
#define IDB_BITMAP_MAGBIFY_SIGN_NORMAL  646
#define IDB_BITMAP_MAGBIGY_SLIDER_BACK  647
#define IDB_BITMAP_MAGBIGY_SLIDER_CHANNEL 647
#define IDD_DLG_ZOOMTITLEBAR            648
#define IDD_DLG_ZOOMDIRCT               649
#define IDB_BITMAP_SOUNDCTRL_SLIDER_CHANNEL_WHITE 651
#define IDB_BITMAP_SOUNDCTRL_SLIDER_CHANNEL_ACTIVE_WHITE 652
#define IDB_BITMAP_NOSOUND_FOCUS_WHITE  653
#define IDB_BITMAP_SOUND_FOCUS_WHITE    654
#define IDB_BITMAP_SOUND_NORMAL_WHITE   656
#define IDB_BITMAP_NOTALKBACK_FOCUS_WHITE 657
#define IDB_BITMAP_NOTALKBACK_NORMAL_WHITE 658
#define IDB_BITMAP_TALKBACK_GRAY_WHITE  659
#define IDB_BITMAP_TALKBACK_NORMAL_WHITE 660
#define IDB_BITMAP_TALKBACK_FOCUS_WHITE 661
#define IDC_BTN_TOOL_REALTIME_EXTEND    800
#define IDC_BTN_TOOL_REALTIME_CAPTURE   801
#define IDS_STR_CAPTURE                 801
#define IDC_BTN_TOOL_REALTIME_RECORD    802
#define IDC_STR_RECORD                  802
#define IDC_BTN_TOOL_REALTIME_LABEL     803
#define IDS_STR_LABEL                   803
#define IDC_BTN_TOOL_REALTIME_MAGNIFY   804
#define IDS_STR_MAGNIFY                 804
#define IDC_BTN_TOOL_REALTIME_INSTANT_BACK_PLAY 805
#define IDS_STR_INSTANT_BP              805
#define IDC_BTN_TOOL_REALTIME_SOUND     806
#define IDS_STR_SOUND                   806
#define IDC_BTN_TOOL_REALTIME_TALKBACK  807
#define IDS_STR_TALK                    807
#define IDC_BTN_TOOL_REALTIME_TVWALL    808
#define IDS_STR_TVWALL                  808
#define IDC_BTN_TOOL_REALTIME_SET_WARN_WND 809
#define IDS_STR_SETWND                  809
#define IDC_BTN_TOOL_REALTIME_PTZ       810
#define IDS_STR_PTZ                     810
#define IDC_BTN_TOOL_REALTIME_SUPER_INTEL 811
#define IDS_STR_SUPERINTEL              811
#define IDC_BTN_TOOL_REALTIME_E_MAP     812
#define IDS_STR_EMAP                    812
#define IDC_BTN_TOOL_REALTIME_MASTER_AUXILIARY 813
#define IDS_STR_MASTERAUXILIARY         813
#define IDC_BTN_TOOL_REALTIME_NET_QUALITY 814
#define IDS_STR_NETQUALITY              814
#define IDC_BTN_TOOL_REALTIME_PTZ3D     815
#define IDS_STR_PTZ3D                   815
#define IDC_BTN_TOOL_REALTIME_RETURN    816
#define IDC_BTN_TOOL_REALTIME_START     817
#define ID_MENU_HEADER                  820
#define ID_MENU_TRAIL                   821
#define ID_MAGNIFY                      32781
#define ID_MINIFY                       32782
#define ID_FULLSCREEN_CHANGE            32783
#define ID_SHOWTITLEBAR_CHANGE          32785

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        662
#define _APS_NEXT_COMMAND_VALUE         32788
#define _APS_NEXT_CONTROL_VALUE         192
#define _APS_NEXT_SYMED_VALUE           125
#endif
#endif
